################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Project
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Any.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ArrayClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ArrayClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Base64.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Base64.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Binding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Binding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/CodeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/CodeGenerator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/CodeLocation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/CodeLocation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Color.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Color.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/CompilationErrors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/CompilationErrors.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Composition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Composition.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ConsoleClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ConsoleClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ConstructorBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Core.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Core.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/DataDrivenLexer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/DataDrivenLexer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/DataDrivenLexer.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Debugging.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Debugging.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Delegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Delegate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/DestructibleBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/DestructibleBuffer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Events.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Events.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ExecutableState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ExecutableState.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/FilePathClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/FilePathClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/FileStreamClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/FileStreamClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Formatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Formatter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ForwardDeclarations.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Function.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Function.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/General.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/GrammarConstants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/GrammarConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Handle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Handle.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/HandleManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/HandleManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/HashContainer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/HashContainer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/InstructionsEnum.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Json.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Json.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Library.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Library.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/LocalBuild.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Matrix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Matrix.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Members.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Members.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/MethodBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/MultiPrimitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/MultiPrimitive.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Opcode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Opcode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/OverloadResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/OverloadResolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Parser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Parser.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Plugin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Plugin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ProcessClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/ProcessClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Project.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Project.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/RandomClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/RandomClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Range.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/RangeBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Setup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Setup.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Sha1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Sha1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Shared.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Shared.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/SharedReference.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StaticLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StaticLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StreamInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StreamInterface.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StringBuilderClass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StringBuilderClass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StringConstants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StringConstants.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StubCode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/StubCode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Syntaxer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Syntaxer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/SyntaxTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/SyntaxTree.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/SyntaxTreeHelpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/SyntaxTreeHelpers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/TemplateBinding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/TemplateBinding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Timer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Timer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Token.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Tokenizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Tokenizer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/TokenReader.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Traits.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Traits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Type.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/UntypedBlockArray.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/VirtualMachine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/VirtualMachine.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/VirtualMethodBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/VirtualTableBinding.inl
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/WebSocket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/WebSocket.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Wrapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Wrapper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Lightning.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Lightning/Lightning.hpp
)
